version: '3.8'

services:
  kafka:
    container_name: kafka
    hostname: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    networks:
      - sritel-network

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 2424M
    networks:
      - sritel-network

  camel-app:
    build:
      context: ./camel/
      dockerfile: dev.Dockerfile
    ports:
      - "8180:8180"
    volumes:
      - ./camel:/app
    depends_on:
      - kafka
    networks:
      - sritel-network


networks:
  sritel-network:
    driver: bridge